{"uuid": "d9e02031-a6bb-43e9-8dc6-419c6230dc07", "children": ["07586f76-1751-4512-b60b-7264041b32e6"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: 'Order' object has no attribute 'url'\n", "trace": "  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\python.py\", line 745, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\conda\\envs\\auto\\lib\\site-packages\\_pytest\\python.py\", line 674, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\company\\auto\\20200606\\lesson12\\apiFrame\\script\\test_order.py\", line 10, in setup_class\n    self.order_obj = Order()\n  File \"D:\\company\\auto\\20200606\\lesson12\\apiFrame\\api\\orderApi.py\", line 8, in __init__\n    log.info(f'提交订单的url地址是{self.url}')\n"}, "start": 1599197819902, "stop": 1599197819902}], "start": 1599197819902, "stop": 1599197819907}